// Automatically generated by astro-icon
// 0287ed9f24eddf62834f49d53dddc0d097e7a43414abd268a051f12f83af2dd6

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "logomark"
		| "theme/dark"
		| "theme/light"
		| "wordmark";
}